apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wfkz9m5tt-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wfkz9m5tt-go 
  name: wfkz9m5tt-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wfkz9m5tt-go 
